import process from 'node:process';

import esbuild from 'esbuild';

const BANNER = `/*
Geode — Obsidian vault backup to Google Drive.
Generated by esbuild from src/. Do not edit.
*/
`;

const production = process.argv[2] === 'production';

/** @type {import('esbuild').BuildOptions} */
const options = {
  entryPoints: ['src/main.ts'],
  bundle: true,
  // Obsidian supplies this module at runtime.
  external: ['obsidian'],
  format: 'cjs',
  platform: 'browser',
  target: 'es2018',
  // Obsidian loads main.js from the plugin folder, next to manifest.json.
  outfile: 'main.js',
  banner: { js: BANNER },
  // Inline in dev so console stack traces point at real source.
  sourcemap: production ? false : 'inline',
  // Not minified: plugin review reads this file, and the size saving is noise.
  minify: false,
  treeShaking: true,
  logLevel: 'info',
};

if (production) {
  await esbuild.build(options);
} else {
  const context = await esbuild.context(options);
  await context.watch();
}
